name: Build and Deploy Angular App to GitHub Pages

# Add this permissions block. This is the critical fix.
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build the application
      # This command builds the app and puts it in a folder named 'dist/The-Universe-Guidance'
      run: ng build --configuration production --base-href /The-Universe-Guidance/

    - name: Setup Pages
      # This step prepares the artifact for deployment
      uses: actions/configure-pages@v3

    - name: Upload artifact
      # This step uploads the finished website from the build folder
      uses: actions/upload-pages-artifact@v2
      with:
        path: './dist/The-Universe-Guidance'

    - name: Deploy to GitHub Pages
      # This step takes the uploaded artifact and deploys it
      id: deployment
      uses: actions/deploy-pages@v2
